### PR TITLE
Deprecate dep in favor of Go Modules

### PR DESCRIPTION
**Pull request by khos2ow**
### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [ ] This pull request adds a feature.
- [x] This pull request enhances existing functionality.
- [ ] This pull request introduces breaking change.

For more information, see the [Contributing Guide](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

This pull request deprecates [dep](https://github.com/golang/dep#dep) in favor of [Go Modules](https://github.com/golang/go/wiki/Modules).

### Issues Resolved

List any existing issues this pull request resolves.

### Checklist

Put an `x` into all boxes that apply:

- [x] I have read the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

#### Tests

- [ ] I have added tests to cover my changes.
- [x] All tests pass when I run `make test`.

#### Documentation

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

#### Code Style

- [ ] My code follows the code style of this project.

### CODE REVIEW

**Comment by metmajer** [comment]
Hey @khos2ow, happy new year! I'll look into Go Modules and your PR in the next days.

**Comment by zimbatm** [comment]
@metmajer isn't CircleCI already doing this for us?

**Comment by metmajer** [comment]
@zimbatm You are correct. I guess I'm just startled that you're giving your approval to a feature that hasn't been commented by the codebase maintainer.

**Comment by zimbatm** [comment]
I was just passing by and happened to look at the PR. I don't think my approval has a lot of weight, except maybe nudge the maintainers?

**Comment by metmajer** [comment]
@khos2ow I am looking into your PR at the moment, but I am getting errors with the latest version of `gometalinter` on my development machine. Obviously, tests are green in CircleCI, but I'll investigate and get back shortly.

**Comment by metmajer** [comment]
`gometalinter` is known to produce issues with go modules. I'll open a PR to replace this one with its alternative `golangci-lint`.

**Comment by metmajer** [comment]
@khos2ow `golangci-lint` has been included with in #103. Please rebase. Otherwise, LGTM!

**Comment by khos2ow** [comment]
Sorry guys, I was AFK for few days!

I agree with @zimbatm , generally everyone can approve any PR, but the ones that matter at the end will be the maitainers'. And that's why there's a color coding of approval (grey vs green).

@metmajer that's weird. I've tried `make lint` on both

- `gometalinter version 2.0.11 built from 17a7ffa42374937bfecabfb8d2efbd4db0c26741 on 2018-09-09T06:19:21Z`
- `gometalinter version 2.0.12 built from 102ac984005d45456a7e3ae6dc94ebcd95c2bb19 on 2018-12-16T00:57:56Z`

and neither failed. but since you already went ahead with #103 it's all good! Thanks.

**Comment by metmajer** [comment]
One of gometalinter's plugins failed due to unresolvable package dependencies even after `go mod vendor` was executed. It appears as if the plugin was looking up those packages in my (then empty) `GO_PATH`, and not in the `vendor` directory. Still, this doesn't explain why we didn't see this error in the pipeline, but overall, `golangci-lint` seems to be the better alternative (and worked fine ootb).

**Comment by khos2ow** [comment]
Hmm, that's strange. I, yet, need to read more about `golangci-lint`. :+1:

**Comment by metmajer** [comment]
I also needed some time to understand the value and impact of Go modules. Since this goes in my spare time, things sometimes take a while. In the future, let's share thoughts in a dedicated Issue before filing a PR (see [Contribution Guide](https://github.com/segmentio/terraform-docs/blob/master/CONTRIBUTING.md)). Thanks for another great contribution, @khos2ow!

**Comment by metmajer** [comment]
Hey @zimbatm! I really don't mind a nudge. Still, there's a difference between nudging and approving someone's work. While @khos2ow PR has been complete and indeed a valuable contribution to this project, we often see things the other round here as well. Just be cautious with giving approvals, and if it's simply about a nudge, I'd value if you'd drop me a message instead. :+1:

**Comment by metmajer** [comment]
@zimbatm By the way, we'd value your contributions if you're inclined. There's a couple of open issues, so feel free to have a look and let me know if you have questions!

**Pull request merged**
