### PR TITLE
Unify description text of inputs and outputs

### LINKED ISSUE #92: Unify behavior of empty Description among different print types
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Following up a discussion in #81 the behavior of _empty_ `Description` needs to be unified between different `print` types. Considering:

- `json`: technically can be remained as empty since empty JSON attribute is meaningful
- `markdown`: one of the following for both `table` and `document`
  - `Description: -`
  - `Description: n/a`
  - `Description: ""`
  - hide `Description` altogether

### PR DESCRIPTION
**Pull request by metmajer**
### Prerequisites

Put an `x` into the box(es) that apply:

- [x] This pull request fixes a bug.
- [ ] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

For more information, see the [Contributing Guide](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

This pull request unifies the rendering of the description texts for inputs and outputs.

### Issues Resolved

#92 

### Checklist

Put an `x` into all boxes that apply:

- [x] I have read the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

#### Tests

- [ ] I have added tests to cover my changes.
- [x] All tests pass when I run `make test`.

#### Documentation

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

#### Code Style

- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by khos2ow** [comment]
Nice! :+1:

**Comment by metmajer** [comment]
Hey @khos2ow! Apologies for stealing the ticket, but I wanted to get this out the door to prepare a new release with your new document format :)

**Comment by khos2ow** [comment]
Not at all @metmajer . I've been very busy myself, otherwise I had the same idea and wanted to actually propose a release before Terraform v0.12 is out so that we might be able to react to that official release and enhance from our side.

**Comment by metmajer** [comment]
Cool, @khos2ow. I've already started working on a feature branch on my local machine. Some interesting references can be found in #62.

**Comment by khos2ow** [comment]
Cool, ping me for any help.

**Pull request merged**
