### PR TITLE
Cleanup HomebrewFormula folder

### PR DESCRIPTION
**Pull request by chenrui333**
As the formula exists in homebrew-core repo, I guess we can remove `HomebrewFormula` folder?

Also, you can automate the release process with https://github.com/mislav/bump-homebrew-formula-action

Relates to https://github.com/Homebrew/homebrew-core/pull/47860

### CODE REVIEW

**Comment by metmajer** [comment]
@chenrui333 we want to keep this formula as a template. Thanks!

**Comment by chenrui333** [comment]
Oh, interesting. What is the idea behind it?

**Comment by khos2ow** [comment]
Actually I was going to to move the top-level `HomebrewFormula` folder under `scripts/homebrew` after Homebrew/homebrew-core#47860 gets merged, for historical references.
+1 on the auto update formula action, will definitely do that.

**Comment by chenrui333** [comment]
`scripts/homebrew`, what is that for?

**Comment by khos2ow** [comment]
Just a local copy of the formula within the repo, for reference.

**Pull request closed without merging**
