### PR TITLE
Add option --with-aggregate-type-defaults to enable printing of default values for types 'list' and 'map'.

### PR DESCRIPTION
**Pull request by metmajer**
### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [x] This pull request adds a feature.
- [x] This pull request introduces breaking change.

For more information, see the [Contributing Guide](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

This pull request adds the `--with-aggregate-type-defaults` option to enable printing of default values for types 'list' and 'map'. If enabled, default values of aggregate types are presented as *JSON* data structures.

**The pull request introduces a breaking change**. The data type `doc.Value` has its property `Literal` changed to `Value`. This shouldn't affect you're making use of `terraform-docs json`, where this change is reflected in the resulting output.

The following example shows the processing of a Terraform variable of type `map`:

```
variable "foo" {
  default = {
    bar = 1
    baz = "two"
  }

  description = "Some variable named 'foo'."
  type = "map"
}
```

```
$ terraform-docs json .

[…]
{
  "Name": "foo",
  "Description": "Some variable named 'foo'.",
  "Default": {
    "Type": "map",
    "Value": {
      "bar": 1,
      "baz": "two"
    }
  },
  "Type": "map"
}
[…]
```

```
$ terraform-docs md .
```

| Name | Description | Type | Default | Required |
|------|-------------|:----:|:-----:|:-----:|
| foo | Some variable named 'foo'. | map | `{ "bar": 1, "baz": "two" }` | no |

```
$ terraform-docs .

[…]
var.foo ({ "bar": 1, "baz": "two" })
Some variable named 'foo'.
[…]
```

### Issues Resolved

- #15
- #47

### Checklist

Put an `x` into all boxes that apply:

- [x] I have read the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

#### Tests

- [x] I have added tests to cover my changes.
- [x] All tests pass when I run `make test`.

#### Documentation

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

#### Code Style

- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by metmajer** [comment]
@yields with the number of pull requests being open since a longer time now, is this project still maintained?

**Comment by yields** [comment]
We use it heavily in segment, however, since I've moved teams I no longer personally use this.
I'll review the PRs over the weekend, sorry about the delay here!

**Comment by metmajer** [comment]
@boggsboggs I am referring to your recent commit https://github.com/segmentio/terraform-docs/commit/7110697c09f357127900dd48381b29f3fabe863c, indicating that this repo is currently unmaintained. I am willing to step in as maintainer or have maintainance transferred over to https://github.com/getcloudnative/terraform-docs. Please let me know if either works for you.

**Comment by boggsboggs** [comment]
Thanks for your patience @metmajer. You're a collaborator with write access to the repo now. I've updated the Readme to reference you and your work and explain the maintenance arrangement to users: https://github.com/segmentio/terraform-docs#maintenance

**Comment by metmajer** [comment]
@boggsboggs Thanks for seeing this through. In order to properly maintain this project for @segmentio, I request admin access to this repository so that I can enlarge the maintenance team if needed. You can reach out to me via metmajer@getcloudnative.io. Thanks!

**Pull request merged**
