### PR TITLE
Show 'providers' information

### PR DESCRIPTION
**Pull request by khos2ow**
### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [x] This pull request adds a feature.
- [ ] This pull request enhances existing functionality.
- [x] This pull request introduces breaking change.

For more information, see the [Contributing Guide](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

This PR adds  new functionality to show `providers` information. This was originally added in #113 by @moatra which we decided to introduce it in its own PR for the sake of cleaner history.

### Issues Resolved

List any existing issues this pull request resolves.

### Checklist

Put an `x` into all boxes that apply:

- [ ] I have read the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

#### Tests

- [x] I have added tests to cover my changes.
- [x] All tests pass when I run `make test`.

#### Documentation

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

#### Code Style

- [ ] My code follows the code style of this project.

### CODE REVIEW

**Comment by metmajer** [comment]
@khos2ow should we display provider information optionally?

**Comment by khos2ow** [comment]
I think after a little while showing provider information will become mainstream, and instead of opt-in approach I had thought to add new flags for opt-out approach, `--no-providers`, `--no-inputs`, `--no-outputs`. What do you think?

**Comment by metmajer** [comment]
@khos2ow I like that approach!

**Comment by crisp2u** [comment]
Guys, how is this supposed to work ? I guess it will show the same output as *Providers Requirements* section from `terraform-config-inspect` ? Or `terraform providers` ? Can you provide some examples based on the test data ?

**Comment by khos2ow** [comment]
@crisp2u it looks for `required_providers` but it's not the only way to look for the providers, we're also looking for all the managed and data resource to discover the providers ([module.go#134](https://github.com/segmentio/terraform-docs/blob/master/internal/pkg/tfconf/module.go#L134)).

Also you can find the generated content [here](https://github.com/segmentio/terraform-docs/blob/master/internal/pkg/print/markdown/table/testdata/table.golden#L1-L8) based on our [example](https://github.com/segmentio/terraform-docs/blob/master/examples/main.tf).

```hcl

**Pull request merged**
