### PR TITLE
Support Terraform 0.12.x configuration

### PR DESCRIPTION
**Pull request by moatra**
This PR is meant as a proposal for adding Terraform 0.12 support.  It replaces the current AST parsing with the [hashicorp/terraform-config-inspect](https://github.com/hashicorp/terraform-config-inspect) module.  

(I picked up golang this weekend to make this change, so I apologize in advance for anything non-idiomatic.  Feedback appreciated!)

Major changes:
* Pulling descriptions from comments is no longer supported.
* Dropped support for the `--no-sort ` flag, as the terraform-config-inspect module doesn't seem to return blocks in source order
* Dropped support for the `--with-aggregate-type-defaults` flag.  All output for `default` is now json.
* Markdown table output for variables is now done using html elements, to support multi line codeblocks for extended types and default values.
* Added the `--providers` flag to include information on the provider configuration needed by the module.
* Dropped the `vendor/` directory
* Changed `path` cli input from multiple directories or files  to just one directory; ([`tfconfig.LoadModule()`](https://github.com/hashicorp/terraform-config-inspect/blob/master/tfconfig/load.go#L14)  only supports loading one directory)

I updated `master` on the fork repo to directly support `go get github.com/moatra/terraform-docs` if you'd like to try it out locally. 

Thoughts?  Concerns?  Changes?

(ref: #62 )

### CODE REVIEW

**Comment by metmajer** [comment]
Hi @moatra, and thanks for your interest in this project! We know that support for Terraform 0.12 is important... and that it's a beast. Although I value your proposal, we can't simply throw away existing functionality from `terraform-docs`, such as the parsing of comments. I am well aware that this will require extensive integration with HCL 2 and the complexity of this migration and the fact that we're into full-time jobs doesn't allow for a quick approach.

I'll have a look at your implementation soon. Please understand though, that this migration has to be done carefully and feature complete and will have to be done by more senior contributors.

**Comment by moatra** [comment]
Hey @metmajer!  I completely understand; this PR is an experiment with using the terraform-config-inspect module to get 80% of the functionality for 20% of the work (and a project for me to learn go).  I realize a lot of the changes in the PR are pretty aggressive, and if there's any future for the PR I'm happy to dial it back.  I strongly doubt terraform-config-inspect will be willing to sniff comments, so if 100% feature support is mandatory, the approach in this PR won't work. 

That said, my gut says that there's probably a good chunk of the terraform-docs user base that needs 0.12 support but not comment sniffing support. If so, is there a path forward with a transient release  using terraform-config-inspect while the dev work for the correct solution is ongoing?

**Comment by cmeisinger** [comment]
My .02 is that I'd love a version which works with .12.   Frankly terraform-docs w/o .12 support is an antiquated tool which makes me sad.

I've already converted a _very_ large TF codebase to .12 and I'm sure I'm not alone.

Halp. :)

**Comment by sudoforge** [comment]
> I've already converted a very large TF codebase to .12 and I'm sure I'm not alone.

Just to throw some additional weight behind this; I have somewhere around 200k lines of HCL that have been converted to HCL2 and previously relied upon `terraform-docs` for generating module documentation.

As I understand it, we are waiting on hashicorp/terraform-config-inspect#17 and hashicorp/terraform-config-inspect#18 -- is there any outstanding work we have to do outside of that to help support pushing an update that works with HCL2?

**Comment by metmajer** [comment]
@sudoforge You may want to look at https://github.com/segmentio/terraform-docs/issues/62 for the current status. We're waiting for [hashicorp/terraform-config-inspect](https://github.com/hashicorp/terraform-config-inspect/) contributors to elaborate on our feature and pull requests. You want to help? Here are a couple of suggestions:

1) You don't have to convince us. We don't like the situation either. There is no easy migration path to HCL2, and I have decided to build on HashiCorp's own _terraform-config-inspect_ project to provide for best backwards and forward compatibility. A custom integration would inevitably leave us one step behind. Like it or not.
2) Push the maintainers at _terraform-config-inspect_ to support our feature request. The project states that pull requests are not supported. Therefore, we need to ask for permission first.
3) @antonbabenko mentions a workaround over at https://github.com/segmentio/terraform-docs/issues/62 which you could use for the time being.
4) If you're relying heavily on terraform-docs and can live with the limitations provided by this pull request, you may want to continue with @moatra's contribution until we have a better solution available.
5) Open source project maintainers don't get paid and run these projects in their spare time. If you think that our path is wrong, I invite you to suggest or provide a better solution.

**Comment by sudoforge** [comment]
@metmajer Woah, hey, it sounds like I may have misworded my earlier comment or that you may be misconstruing it; I was legitimately asking what was still outstanding so that I could help out (either via code or other means).

From one FOSS maintainer to another, many apologies.

---

I'll bug Hashicorp, and take a look at resolving the conflicts in this PR.

**Comment by moatra** [comment]
Here's a summary of where things stand today for generating Terraform 0.12 module docs:

* **terraform-docs**: Since comment support is required for the next official release of `terraform-docs`, this PR is blocked on hashicorp/terraform-config-inspect#21.  When (if) that lands, this PR will need some more work to adapt the new feature and re-enable source sorting for variables.
* **terraform-docs fork**:  [My fork](https://github.com/moatra/terraform-docs) of the repo enables you to `go get github.com/moatra/terraform-docs` to install the 0.12 enabled version from this PR. (NB: no guarantees on maintenance for that repo, sorry)
* **awk workaround**: The [antonbabenko/pre-commit-terraform](https://github.com/antonbabenko/pre-commit-terraform) repo has a [shell script](https://github.com/antonbabenko/pre-commit-terraform/blob/master/terraform_docs.sh) that should enable the current `terraform-docs` to work on 0.12 sources
* **terraform-config-inspect**:  You can use the [`terraform-config-inspect`](https://github.com/hashicorp/terraform-config-inspect) binary today to generate markdown for a module.  However, there's no way to change the output format.   The hashicorp/terraform-config-inspect#17 PR will let you specify your own go template, which could make `terraform-config-inspect` a viable alternative to `terraform-docs`

**Comment by jstewmon** [comment]
You could use `terraform-config-inspect -json` with [gomplate](https://docs.gomplate.ca/usage/) to format however you like.

**Comment by metmajer** [comment]
@jstewmon How would this be more helpful as opposed to using this PR? terraform-config-inspect lacks features that we depend on to remain feature compatible.

**Comment by jstewmon** [comment]
@metmajer I was just offering a suggestion in direct response to this line in @moatra's comment:
> You can use the terraform-config-inspect binary today to generate markdown for a 0.12 module. **However, there's no way to change the format of the markdown.** The hashicorp/terraform-config-inspect#17 PR will let you specify your own go template, which could make terraform-config-inspect a viable alternative to terraform-docs

**Comment by njunxuan** [comment]
Hi, I am interested in contributing towards this PR. Are the primary blockers for this PR the lack of pulling description from comments and the lack of the `--no-sort` flag?

**Comment by metmajer** [comment]
@njunxuan Thank you for offering your support! @khos2ow and I have decided to move on with this approach and sacrifice support for comments for the time being. And, you name it, support for `--no-sort` can be added by inspecting line numbers. @khos2ow let @njunxuan know if he can help in some way.

**Comment by njunxuan** [comment]
should we keep 0.12 support behind a flag so that we do not break existing workflows?

**Comment by khos2ow** [comment]
@moatra I just created branch `terraform-012` based off of the commit you had created this PR from. Would you be able to change the target of this PR that we can go ahead and merge it in `terraform-012`? Then we can start rebasing on master and fixing the conflicts from there.

**Comment by khos2ow** [comment]
I'm in the middle of rebasing this PR and resolving the conflicts. I want to propose these changes while doing so:

- remove `--providers` flag from here and add it in its own standalone PR for the sake of documentation and history
- don't drop the support for `--no-sort` here because we've kinda figured out a way, and actually implement that in its own PR
- don't drop the support for `--with-aggregate-type-defaults` altogether because it's a breaking change, rather than having it around (while internally doing nothing) and communicate the upcoming change and completely deprecate it in the following first or second release from now
- don't rename from `input` to `variable` in here. I love the notion of deprecating _input_ in favor of _variables_ (which is a more natural Terraform wording) but it's gonna be a slight breaking change and doing so will introduce a lot of changes to existing markdown of the downstream users. May be we can come up with an opt-in support for it and eventually deprecate it in the following release or two

What I have in mind is to continue with the rebase and resolve all the conflicts and on the consecutive commits here apply the above changes I mentioned and finally proceed with this PR.
 
@moatra I'd love your feedback on this, and also from all the other folks here.

/cc @metmajer

**Comment by sudoforge** [comment]
@khos2ow I agree with the changes you have proposed; keeping PRs as small and focused as possible is a great goal.

**Comment by khos2ow** [comment]
I'm done with rebasing and fixing the issues. I've used the binary of this PR on some real world config of my own and some from opensource community, and the amount of different is minimal and acceptable. Although I suspect that's gonna grow because we're going to add `provider` and `variable` name in another PR, but still it'll be acceptable.

I'm gonna merge this PR now and continue on the points I mentioned earlier on consecutive PRs.

**Comment by metmajer** [comment]
Thanks @khos2ow for taking the lead on this one and making it happen!

**Comment by kmfk** [comment]
@khos2ow I'm excited to see this merged, what was the plan for tagging a release?

**Comment by khos2ow** [comment]
@kmfk I just came back from holiday break, I'm targeting to cut a RC release sometime next week.

**Pull request merged**
