### PR TITLE
Bump golang to latest v1.13

### PR DESCRIPTION
**Pull request by chenrui333**
### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [ ] This pull request adds a feature.
- [x] This pull request enhances existing functionality.
- [ ] This pull request introduces breaking change.

For more information, see the [Contributing Guide](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Bump golang version to latest v1.13 (1.13.5), as brew formula is already using it (https://github.com/Homebrew/homebrew-core/pull/47860)

### Checklist

Put an `x` into all boxes that apply:

- [x] I have read the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

#### Tests

- [ ] I have added tests to cover my changes.
- [ ] All tests pass when I run `make test`.

#### Documentation

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

#### Code Style

- [ ] My code follows the code style of this project.

### CODE REVIEW

**Comment by chenrui333** [comment]
Could not find the circle-ci config, I guess it has been removed? The gh-actions builds are green though.

**Comment by khos2ow** [comment]
Thanks @chenrui333 , yeah we removed the circleci config but not the webhooks. I'll merge this later when not AFK.

**Comment by chenrui333** [comment]
I see, sounds good!!

**Comment by khos2ow** [comment]
@chenrui333 I saw you merged the formula PR, I was wondering if we're blocked by this change or not? The reason is I'm in the middle of rebasing a PR with a lot of conflict and I hoped to not merge anything to master before completing that.

**Comment by chenrui333** [comment]
It is blocked by this PR, it would be nice to keep golang version consistent though.

**Comment by khos2ow** [comment]
Thank you @chenrui333 :heart:

**Comment by chenrui333** [comment]
Happy to help, thanks for the merge!

**Comment by kmfk** [comment]
@khos2ow Pretty excited to see this get in - any chance we can get this tagged as a release?

**Pull request merged**
